pizzas/urls.py
from django.urls import path
from . import views

app_name = 'pizzas'

urlpatterns = [
    path('', views.index, name='index'),
    path('pizzas/', views.my_pizzas, name='my_pizzas'),
    path('pizzas/<int:pizza_id>', views.pizza, name='pizza'),

]

pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("pizzas.urls"))
]

pizzas/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
    """An object to handle Pizza's"""
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.name


class Topping(models.Model):
    """A class managing to pazza's topping"""
    name = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    pizza_name = models.CharField(max_length=100, default="pineapple")
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'toppings'

    def __str__(self) -> str:
        return self.pizza_name
    

pizzas/views.py
from multiprocessing import context
from urllib import request
from django.shortcuts import render
from .models import Pizza

# Create your views here.
def index(request):
    return render(request, "pizzas/index.html")

def my_pizzas(request):
    """Show all pizzas"""
    pizzas = Pizza.objects.order_by('date_added')
    contexts = {'pizzas': pizzas}
    return render(request, "pizzas/my_pizzas.html", contexts)

def pizza(request, pizza_id):
    """Show a signle pizza with it entries."""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('name') # topping_set is used because of the have topping model name
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, "pizzas/pizza.html", context)

pizzas/templates/pizzas/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pizza's Resturant</title>
</head>
<body>
    <p><a href="{% url 'pizzas:index' %}">Home</a> -
        <a href="{% url 'pizzas:my_pizzas' %}">Pizzas</a>
    </p>

  {% block content %}
    
  {% endblock %}
</body>
</html>

pizzas/templates/pizzas/index.html
{% extends 'pizzas/base.html' %}

{% block content %}
    <h1>Welcome to Pizza Resturant!!</h1>
    <p>Your best resturant for pizzas in the gambia.</p>
{% endblock %}

pizzas/templates/pizzas/my_pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}
    <h1>Pizzas:</h1>
    <ul>
        {% for pizza in pizzas %}
            <li><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a> </li>
        {% empty %}
            <li>No pizza is available here yet.</li>
        {% endfor %}
    </ul>
{% endblock %}

pizzas/templates/pizzas/pizza.html
{% extends 'pizzas/base.html' %}
{% block content %}
<h1>Pizza: {{ pizza }} </h1>
<p>Toppings:</p>
<ul>
    {% for topping in toppings %}
     <li>
        <p> {{ topping.date_added|date:'M d, Y H:i' }}</p>
        </li>
        <li>
            <p> {{ topping.pizza_name }}</p>
        </li>
    {% empty %}
     <li>No topping added yet.</li>
    {% endfor %}
        
</ul>
{% endblock %}